#!/usr/bin/env bash
#
# This test builds a package, installs it in a temporary virtual environment,
# and runs the unit tests.

python -m build --wheel && \
TEST_VENV=$(mktemp -d) && \
python -m venv $TEST_VENV && \
$TEST_VENV/bin/pip install dist/*.whl && \
cd test && \
$TEST_VENV/bin/python -m unittest discover -s .
TEST_RESULT=$?
rm -r $TEST_VENV
exit $TEST_RESULT
